---
title: "The Great British Bake Off"
author: "Alison Hill"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: readable
params:
  series:
    label: "Series:"
    value: 1
    input: numeric
    min: 1
    max: 9
    step: 1
  palette: 
    label: "Wes Anderson palette:"
    value: "GrandBudapest1"
    input: select
    choices: [GrandBudapest1, Darjeeling1, Darjeeling2, FantasticFox1, Royal2]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE,
                      fig.path = "alison-figs/")
library(tidyverse)
library(here)
library(glue)
library(wesanderson)
theme_set(theme_minimal())
```

```{r import-data, include=FALSE}
filepath <- glue::glue("data/ratings-{params$series}.csv")
ratings <- readr::read_csv(here::here(filepath)) %>% 
  mutate(episode = as.factor(episode))
```


# Overview

Series `r params$series` premiered on `r min(ratings$uk_airdate)`, and had `r n_distinct(ratings$episode)` episodes.

# Ratings

```{r ratings-by-episode}
viewers <- ratings %>% 
  select(series:viewers_28day) %>% 
  pivot_longer(starts_with("viewers"), 
    names_to = "days", 
    names_prefix = "viewers_", 
    values_to = "viewers"
  ) 
ggplot(viewers, 
       aes(episode, viewers, 
           colour = days, group = days)
       ) + 
  geom_point() + 
  geom_line() + 
  labs(
    x = "Episode", 
    y = "Viewers (millions)"
  ) +
  expand_limits(y = 0) +
  scale_colour_manual(values = wes_palette(params$palette))
```
